dist: trusty
sudo: required
language: node_js
node_js:
 - "6"
services:
 - mongodb
env:
 - MONGOHQ_URL=mongodb://127.0.0.1/reactors
after_script:
  - npm run coveralls
before_install:
 - export CHROME_BIN=chromium-browser
 

 